=== krazzei/engine3d/plugins/OpenCOLLADA-master/xsd2cppsax/tests/validation_complex_types/t04.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    This test handles different compositors in different elements (no nested ModelGroups).
    minOccurs=0, minOccurs=1 and maxOccurs unbounded are tested as well.
 -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.netallied.de/xsd2cppsax/tests" xmlns:tns="http://www.netallied.de/xsd2cppsax/tests" elementFormDefault="qualified">

    <element name="root" type="tns:RootType"></element>

	<complexType name="RootType">
		<all>
			<element name="allElem1" minOccurs="1" maxOccurs="1" type="tns:SequenceType" />
			<element name="allElem2" minOccurs="0" maxOccurs="1" type="tns:SequenceType2" />
			<element name="allElem3" minOccurs="1" maxOccurs="1" />
		</all>
	</complexType>

	<complexType name="SequenceType">
		<sequence>
			<element name="seqElem1" minOccurs="1" maxOccurs="2" type="tns:ChoiceType" />
			<element name="seqElem2" minOccurs="0" maxOccurs="2" />
			<element name="seqElem3" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="SequenceType2"><!-- first two elements with minOccurs="0" -->
		<sequence>
			<element name="seq2Elem1" minOccurs="0" maxOccurs="2" />
			<element name="seq2Elem2" minOccurs="0" maxOccurs="2" />
			<element name="seq2Elem3" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="ChoiceType">
		<choice>
			<element name="choiceElem1" minOccurs="1" maxOccurs="2" />
			<element name="choiceElem2" minOccurs="0" maxOccurs="2" />
			<element name="choiceElem3" minOccurs="1" maxOccurs="unbounded" />
		</choice>
	</complexType>

</schema>

=== krazzei/engine3d/plugins/OpenCOLLADA-master/xsd2cppsax/tests/validation_complex_types/t04_03.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="http://www.netallied.de/xsd2cppsax/tests"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.netallied.de/xsd2cppsax/tests t04.xsd"
      >
	<allElem1>
		<!-- seqElem1 occurs two times -->
		<seqElem1>
			<choiceElem2 /><!-- choiceElem2 occurs two times -->
			<choiceElem2 />
		</seqElem1>
		<seqElem1>
			<choiceElem2 /><!-- choiceElem1 occurs once -->
		</seqElem1>
		<seqElem2 />
		<seqElem3 />
	</allElem1>

	<allElem2>
		<seq2Elem1 />
		<!-- seq2Elem2 is not present -->
		<seq2Elem3 />
	</allElem2>

	<allElem3 />
</root>

=== krazzei/engine3d/plugins/OpenCOLLADA-master/xsd2cppsax/tests/validation_complex_types/t04_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="http://www.netallied.de/xsd2cppsax/tests"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.netallied.de/xsd2cppsax/tests t04.xsd"
      >
    <!-- allElem2 is not present -->
	<allElem3 /><!-- allElem3 occurs before allElem1 -->
	<allElem1>
		<seqElem1 /><!-- seqElem1 is empty, that means choiceElem2 is chosen with occurrence = 0 -->
		<!-- seqElem2 is not present -->
		<seqElem3 /><!-- seqElem3 occurs multiple times -->
		<seqElem3 />
		<seqElem3 />
		<seqElem3 />
		<seqElem3 />
		<seqElem3 />
		<seqElem3 />
	</allElem1>
</root>

=== krazzei/engine3d/plugins/OpenCOLLADA-master/xsd2cppsax/tests/validation_complex_types/t04_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="http://www.netallied.de/xsd2cppsax/tests"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.netallied.de/xsd2cppsax/tests t04.xsd"
      >
	<allElem3 /><!-- allElem3 occurs before allElem1 -->
	<allElem1>
		<!-- seqElem1 occurs two times -->
		<seqElem1>
			<choiceElem1 /><!-- choiceElem1 occurs two times -->
			<choiceElem1 />
		</seqElem1>
		<seqElem1>
			<choiceElem3 /><!-- choiceElem3 occurs multiple times -->
			<choiceElem3 />
			<choiceElem3 />
			<choiceElem3 />
			<choiceElem3 />
			<choiceElem3 />
			<choiceElem3 />
			<choiceElem3 />
		</seqElem1>
		<seqElem2 />
		<seqElem3 />
	</allElem1>

	<allElem2>
		<!-- seq2Elem1 and seq2Elem2 are not present -->
		<seq2Elem3 /><!-- seq2Elem3 occurs multiple times -->
		<seq2Elem3 />
		<seq2Elem3 />
		<seq2Elem3 />
		<seq2Elem3 />
	</allElem2>
</root>
