=== krazzei/engine3d/plugins/OpenCOLLADA-master/xsd2cppsax/test_suite.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.netallied.de/xsd2cppsax/testsuite"
           targetNamespace="http://www.netallied.de/xsd2cppsax/testsuite"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="testSuite_type">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="test" type="test_type" />
		</xs:sequence>
		<xs:attribute name="outDir" use="required" type="xs:token" />
	</xs:complexType>

	<xs:complexType name="test_type">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="document" type="document_type" />
		</xs:sequence>
		<xs:attribute name="config" use="required" type="xs:token" />
		<xs:attribute name="input" use="required" type="xs:token" />
		<xs:attribute name="rootElement" use="required" type="xs:token" />
	</xs:complexType>

	<xs:complexType name="document_type">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="expectedError" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="input" use="required" type="xs:token" />
		<xs:attribute name="output" use="required" type="xs:token" />
	</xs:complexType>

	<xs:element name="TestSuite" type="testSuite_type" />

</xs:schema>

=== krazzei/engine3d/plugins/OpenCOLLADA-master/xsd2cppsax/test_suite.xml
<?xml version="1.0" encoding="UTF-8"?>
<TestSuite xmlns="http://www.netallied.de/xsd2cppsax/testsuite"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.netallied.de/xsd2cppsax/testsuite test_suite.xsd"
           outDir="tests_output">

	<!-- test XSDs -->
	<test config="config/testing.conf" input="tests/t04.xsd" rootElement="root">
		<document input="tests/t04.xml" output="t04_01.xml">
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithBoolListAttribute, Attribute: boolList, Line: 33, Column: 40, Additional:  f t</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithBoolListAttribute, Attribute: boolList, Line: 34, Column: 40, Additional:  t f</expectedError>
		</document>
		<document input="tests/t04_02.xml" output="t04_02.xml" />
		<document input="tests/t04_03.xml" output="t04_03.xml" />
		<document input="tests/t04_inf_nan.xml" output="t04_inf_nan.xml">
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatList, Line: 13, Column: 54, Additional: INFa +INF1 -INF. +Na</expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatList, Line: 14, Column: 49, Additional: INF1 -INF. +NaN -NaN</expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatList, Line: 15, Column: 43, Additional: INF. +NaN -NaN NaNa</expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatList, Line: 16, Column: 37, Additional: NaN -NaN NaNa NaN1 N</expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatList, Line: 17, Column: 32, Additional: NaN NaNa NaN1 NaN.</expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatList, Line: 18, Column: 27, Additional: NaNa NaN1 NaN.</expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatList, Line: 19, Column: 22, Additional: NaN1 NaN.</expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatList, Line: 20, Column: 17, Additional: NaN.</expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatElement, Line: 29, Column: 35, </expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatElement, Line: 30, Column: 36, </expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatElement, Line: 31, Column: 36, </expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatElement, Line: 32, Column: 35, </expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatElement, Line: 33, Column: 35, </expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatElement, Line: 34, Column: 35, </expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatElement, Line: 35, Column: 35, </expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: FloatElement, Line: 36, Column: 35, </expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatListAttribute, Attribute: listAttr, Line: 42, Column: 41, Additional: INFa +INF1 -INF. +Na</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatListAttribute, Attribute: listAttr, Line: 43, Column: 41, Additional: INF1 -INF. +NaN -NaN</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatListAttribute, Attribute: listAttr, Line: 44, Column: 41, Additional: INF. +NaN -NaN NaNa</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatListAttribute, Attribute: listAttr, Line: 45, Column: 41, Additional: NaN -NaN NaNa NaN1 N</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatListAttribute, Attribute: listAttr, Line: 46, Column: 41, Additional: NaN NaNa NaN1 NaN.</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatListAttribute, Attribute: listAttr, Line: 47, Column: 41, Additional: NaNa NaN1 NaN.</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatListAttribute, Attribute: listAttr, Line: 48, Column: 41, Additional: NaN1 NaN.</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatListAttribute, Attribute: listAttr, Line: 49, Column: 41, Additional: NaN.</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatAttribute, Attribute: floatAttr, Line: 58, Column: 38, Additional: INFa</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatAttribute, Attribute: floatAttr, Line: 59, Column: 38, Additional: +INF1</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatAttribute, Attribute: floatAttr, Line: 60, Column: 38, Additional: -INF.</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatAttribute, Attribute: floatAttr, Line: 61, Column: 38, Additional: +NaN</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatAttribute, Attribute: floatAttr, Line: 62, Column: 38, Additional: -NaN</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatAttribute, Attribute: floatAttr, Line: 63, Column: 38, Additional: NaNa</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatAttribute, Attribute: floatAttr, Line: 64, Column: 38, Additional: NaN1</expectedError>
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: ElementWithFloatAttribute, Attribute: floatAttr, Line: 65, Column: 38, Additional: NaN.</expectedError>
		</document>
	</test>

	<test config="config/testing.conf" input="tests/t05.xsd" rootElement="root">
		<document input="tests/t05.xml" output="t05_01.xml">
			<expectedError>Error: ERROR_ATTRIBUTE_PARSING_FAILED Element: stringAttrAtomic, Attribute: stringEnumAtomic, Line: 6, Column: 36, Additional: foo</expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: stringDataAtomic, Line: 21, Column: 21</expectedError>
			<expectedError>Error: ERROR_TEXTDATA_PARSING_FAILED Element: floatDataAtomic, Line: 26, Column: 20</expectedError>
		</document>
	</test>

	<test config="config/testing.conf" input="tests/t06.xsd" rootElement="root">
		<document input="tests/t06.xml" output="t06_01.xml" />
	</test>

	<test config="config/testing.conf" input="tests/t07.xsd" rootElement="root">
		<document input="tests/t07.xml" output="t07_01.xml" />
	</test>

	<test config="config/testing.conf" input="tests/t08.xsd" rootElement="root">
		<document input="tests/t08.xml" output="t08_01.xml" />
	</test>

	<test config="config/testing.conf" input="tests/t09.xsd" rootElement="root">
		<document input="tests/t09.xml" output="t09_01.xml" />
		<document input="tests/t09_02.xml" output="t09_02.xml" />
		<document input="tests/t09_03.xml" output="t09_03.xml">
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: int_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: bool_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: string_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: enum_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: union_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: uri_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: intList_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: boolList_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: stringList_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: enumList_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: unionList_attr, Line: 11, Column: 31, Additional:</expectedError>
			<expectedError>Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: attributeHolderAttrsRequired, Attribute: uriList_attr, Line: 11, Column: 31, Additional:</expectedError>
		</document>
	</test>

	<test config="config/testing.conf" input="tests/t10.xsd" rootElement="root">
		<document input="tests/t10.xml" output="t10_01.xml" />
	</test>

	<test config="config/testing.conf" input="tests/t11.xsd" rootElement="root">
		<document input="tests/t11_01.xml" output="t11_01.xml" />
	</test>

	<test config="config/testing.conf" input="tests/t12.xsd" rootElement="root">
		<document input="tests/t12_01.xml" output="t12_01.xml" />
	</test>

	<!-- simple type validation -->
	<test config="config/testing.conf" input="tests/validation_simple_types/t01.xsd" rootElement="root">
		<document input="tests/validation_simple_types/t01_01.xml" output="validation_simple_types__t01_01.xml" />
